### ISSUE TITLE
Add byte unit

### ISSUE THREAD

**Issue by stefnotch** [gissehel/BarLauncher-UnitConverter#5]
I'm a software engineer, and would love to have a built-in byte unit.
`1 byte` = `8 bit`

**Comment by gissehel** [comment]
It's built-in.

![image](https://user-images.githubusercontent.com/199364/179681765-42021a6e-b992-4b49-adf6-6b083de97c7c.png)

Byte : B
Bit : bit

Note that you can also add your own units:
Ex:

```
unit DVD=4.7GiB
```
![image](https://user-images.githubusercontent.com/199364/179682078-e29b6f55-f89a-4bc1-b1b0-ea45506be3fb.png)

You can then use DVD as a unit with value 4.7GiB (=4.7*1024*1024*1024 B) (=4.7*1024*1024*1024*8 bit)
and use all prefixes like `kDVD`:

![image](https://user-images.githubusercontent.com/199364/179682508-9b4f1d56-e219-4714-9137-c77043beb29e.png)

**Comment by gissehel** [comment]
Can I close the issue ?

**Comment by gissehel** [comment]
Also, with `unit search unit` (and `unit search prefix` for all prefixes) you can display the units currently know by your system:

![image](https://user-images.githubusercontent.com/199364/179687008-47ee63a6-df56-469c-8ada-e6b7626cc71e.png)

and see the abreviation used.

**Comment by stefnotch** [comment]
Oh, lovely! Thanks for bringing that to my attention.
(I was slightly expecting to also be able to type out the name of the unit)
